name: Deploy Everything
on:
  push:
    branches:
      - master
    
jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      is-valid-commit: ${{ steps.check-commit-message.outputs.is-valid-commit }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get the commit message
      id: get-commit-message
      run: echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

    - name: Validate commit message
      id: check-commit-message
      run: |
        if [[ "$message" =~ goownv\sPackage=[0-4]{1}\sVersioning=(Patch|Major|Minor|Specific|ReleaseCandidate)\sIsAutomatic=(true|false)\sMinutesToWait=[0-9]{1}\sAddingNumberToCurrentVersion=[0-9]{1}\sSpecificVersion=(null|[0-9A-Za-z\.]+)\sIsDebug=(true|false): ]]; then
          echo "is-valid-commit=true" >> $GITHUB_ENV
        else
          echo "is-valid-commit=false">> $GITHUB_ENV
        fi

  conditional-job:
    needs: check-commit-message
    if: ${{ $is-valid-commit == 'true' }}
    name: build, pack & publish
    runs-on: windows-latest
    environment: Test
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Commit and Push changes
        run: |
            git config --global user.email "alessandro.rapiti44@gmail.com"    
            cd TestAutoPullWithGitHubAction/bin/Release/net8.0/
            git remote remove origin
            git remote add origin https://KeyserDSoze:${{ secrets.TOKEN }}@github.com/KeyserDSoze/TestAutoPullWithGitHubAction.git
            git remote set-url origin https://KeyserDSoze:${{ secrets.TOKEN }}@github.com/KeyserDSoze/TestAutoPullWithGitHubAction.git
            ls
            ./TestAutoPullWithGitHubAction.exe path=../../../../ v=1.2.3 t=${{ secrets.TOKEN }}
            
      