name: New Event
on:
  push:
    branches:
      - master
    paths:
      - TestAutoPullWithGitHubAction/newFile.txt
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: Test
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.TOKEN }}
      - name: Go ahead
        run: |
            git config --global "alessandro.rapiti44@gmail.com"